// Generates edge copies of the shared real-time code (src/gen/) so the local Node server and the Cloudflare
// deployment run the same source modules. Node-only pieces are swapped for edge equivalents:
//   lib.mjs            ROOT/DATA_DIR become constants; readState/writeState use an in-memory Map that the
//                      Durable Object hydrates from and persists to its storage (exported as __state)
//   sources/index.mjs  static imports instead of fs.existsSync + dynamic import
//   core/persist.mjs   no-op file persistence (the Durable Object persists instead)
// Run: node build.mjs   (wrangler runs it automatically via [build] in wrangler.toml)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const GEN = path.join(HERE, 'src', 'gen');
fs.rmSync(GEN, { recursive: true, force: true });
fs.mkdirSync(path.join(GEN, 'sources'), { recursive: true });
fs.mkdirSync(path.join(GEN, 'core'), { recursive: true });

// ---- lib.mjs
let lib = fs.readFileSync(path.join(ROOT, 'lib.mjs'), 'utf8');
lib = lib.replace(/^import fs from 'node:fs';\n/m, '').replace(/^import path from 'node:path';\n/m, '').replace(/^import \{ fileURLToPath \} from 'node:url';\n/m, '');
lib = lib.replace(/export const ROOT = .*\n/, "export const ROOT = '/';\n");
lib = lib.replace(/export const DATA_DIR = .*\n/, "export const DATA_DIR = '/data';\n");
const rs = lib.indexOf('export function readState(');
const ws = lib.indexOf('export function writeState(');
if (rs < 0 || ws < 0) throw new Error('lib.mjs: readState/writeState not found');
const wsEnd = lib.indexOf('\n}\n', ws) + 3;
lib = `${lib.slice(0, rs)}/** Edge: state lives in this Map; the Durable Object loads it at startup and persists changes. */
export const __state = new Map();
export const __stateDirty = { v: false };
export function readState(name, fallback) {
  return __state.has(name) ? JSON.parse(JSON.stringify(__state.get(name))) : fallback;
}
export function writeState(name, value) {
  __state.set(name, JSON.parse(JSON.stringify(value)));
  __stateDirty.v = true;
}
${lib.slice(wsEnd)}`;
if (/node:/.test(lib)) throw new Error('lib.mjs still imports node: modules');
fs.writeFileSync(path.join(GEN, 'lib.mjs'), `// GENERATED by edge/build.mjs from ../lib.mjs; do not edit.\n${lib}`);

// ---- source modules (import '../lib.mjs' resolves to gen/lib.mjs)
const MODS = ['weather.mjs', 'water.mjs', 'move.mjs', 'civic.mjs', 'extra.mjs', 'tracks.mjs', 'intel.mjs'];
const HELPERS = ['gtfsrt.mjs', 'lookup.mjs', 'webpush.mjs', 'satellite.mjs', 'passes.mjs']; // imported by source modules; not source lists themselves
for (const m of MODS) {
  const src = fs.readFileSync(path.join(ROOT, 'sources', m), 'utf8');
  if (/from 'node:/.test(src)) throw new Error(`${m} imports a node: module`);
  fs.writeFileSync(path.join(GEN, 'sources', m), `// GENERATED by edge/build.mjs from ../sources/${m}; do not edit.\n${src}`);
}
for (const m of HELPERS) {
  const src = fs.readFileSync(path.join(ROOT, 'sources', m), 'utf8');
  if (/from 'node:/.test(src)) throw new Error(`${m} imports a node: module`);
  fs.writeFileSync(path.join(GEN, 'sources', m), `// GENERATED by edge/build.mjs from ../sources/${m}; do not edit.\n${src}`);
}
let index = fs.readFileSync(path.join(ROOT, 'sources', 'index.mjs'), 'utf8');
index = index.replace(/^import fs from 'node:fs';\n/m, '').replace(/^import \{ fileURLToPath \} from 'node:url';\n/m, '');
const staticImports = MODS.filter((m) => m !== 'intel.mjs').map((m, i) => `import * as m${i} from './${m}';`).join('\n');
const table = `const LOADED = { ${MODS.filter((m) => m !== 'intel.mjs').map((m, i) => `'${m}': m${i}`).join(', ')} };`;
index = index.replace("import { INTEL } from './intel.mjs';", `import { INTEL } from './intel.mjs';\n${staticImports}\n${table}`);
index = index.replace("    const url = new URL(`./${file}`, import.meta.url);\n    if (!fs.existsSync(fileURLToPath(url))) continue; // optional module (e.g. extra.mjs) not written yet\n", "    if (!LOADED[file]) continue;\n");
index = index.replace('      mod = await import(url);', '      mod = LOADED[file];');
if (/fs\.|import\(url\)/.test(index)) throw new Error('sources/index.mjs transform failed');
fs.writeFileSync(path.join(GEN, 'sources', 'index.mjs'), `// GENERATED by edge/build.mjs from ../sources/index.mjs; do not edit.\n${index}`);

// ---- core: scheduler helpers, activity log, history store (pure logic) + a no-op persist
for (const m of ['scheduler.mjs', 'activity.mjs', 'history.mjs']) {
  const src = fs.readFileSync(path.join(ROOT, 'core', m), 'utf8');
  if (/from 'node:/.test(src)) throw new Error(`core/${m} imports a node: module`);
  fs.writeFileSync(path.join(GEN, 'core', m), `// GENERATED by edge/build.mjs from ../core/${m}; do not edit.\n${src}`);
}
fs.writeFileSync(path.join(GEN, 'core', 'persist.mjs'), `// GENERATED edge stub: the Durable Object persists state in its own storage.
export const readJson = (file, fallback) => fallback;
export const writeJsonAtomic = () => {};
export function throttledSaver() { return { mark() {}, flush() {}, stop() {} }; }
`);
console.log(`edge build: ${MODS.length} source modules + lib + core -> ${path.relative(HERE, GEN)}`);
